---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: template-repo-sccm
  namespace: ansible-automation-platform
spec:
  connection_secret: controller-token
  name: Template Repository SCM Credential
  organization: Template
  type: Source Control
  description: SCCM credential for private GitHub repository
  # ssh_secret: ssh-private-key-secret
  # ssh_username: ansible
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: template-aap-credential
  namespace: ansible-automation-platform
spec:
  connection_secret: controller-token
  name: Template AAP Credential
  organization: Template
  type: Machine
  description: AAP Connection Secret for Configuration as Code
  # ssh_secret: ssh-private-key-secret
  # ssh_username: ansible