---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleInventory
metadata:
  name: template-configuration-inventory
  namespace: automation
spec:
  connection_secret: controller-token
  name: Template - Configuration as Code Inventory
  organization: Template
  description: Inventory for development environment