---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: deploy-web-app
  namespace: automation
spec:
  connection_secret: controller-token
  name: Template - Configure AAP
  project: Template Use Case
  playbook: playbooks/configure_aap.yml
  inventory: Template - Configuration as Code Inventory
  credentials: 
    - Template AAP Credential