---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleProject
metadata:
  name: private-playbooks
  namespace: automation
spec:
  connection_secret: controller-token
  name: Template Use Case
  organization: Template
  scm_type: git
  repo: https://github.com/Megalith-Development/Ansible-Template-Repo.git
  branch: main
  scm_credential: Template Repository SCM Credential
  description: Template Repostiory for Ansible Automation Platform Use Case